spring.application.name=LearningRestApi


spring.datasource.url=jdbc:postgresql://localhost:5432/StudentDB    //here postgres is our DB name
spring.datasource.username= // username that you have given while installing postgres
spring.datasource.password= // password that you have specified while installing postgres
spring.jpa.hibernate.ddl-auto=update //This will create schema on running your application and will also drop all schemas once you stop your application
spring.jpa.show-sql=true // TO see all the sql statements runned by hibernate 
spring.jpa.properties.hibernate.format_sql=true //Format the hibernate queries, statements